server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: exchange-service
        uri: lb://exchange-service
        predicates:
        - Path=/exchange-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
