server:
  port: 8100

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/book?useTimezone=true&serverTimezone=UTC
    username: ${BOOK_DATABASE_USER}
    password: ${BOOK_DATABASE_PASSWORD}
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3307
    schemas: book
    user: ${BOOK_DATABASE_USER}
    password: ${BOOK_DATABASE_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true

springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
